---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Lady dear, if Fairies may

For a moment lay aside

Cunning tricks and elfish play,

’Tis at happy Christmas-tide.

We have heard the children say -

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Brown lived at such a lofty farm

That everyone for miles could see

His lantern when he did his chores

In winter after half-past three.

And many must have seen him make

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,

Shining with all his might:

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Like fruit that’s large and ripe and mellow,

Sweet and luscious is Longfellow,

Melodious songs he oft did pour,

And high was his Excelsior.

He shows us in his psalm of life

The folly of our selfish strife;

With Hiawatha we bewail

His suffering in great Indian tale;

Indian nation was forlorn

Till great spirit planted corn.
